### ISSUE TITLE
User can look up data on popular cryptocurrencies

### ISSUE THREAD

**Issue by omidzed** [omidzed/ajax-project-1023#1]
## 🖼️ Wireframes

![1696613694387-f2fd5a92-24a1-49f7-8269-a56c50fa3d00_2](https://github.com/omidzed/ajax-project/assets/136918229/90abfb19-7be1-4642-8aa2-68596e69c2ed)

![1696614336212-1be428c1-bc9c-405d-98e4-9a8bce6baaec_2](https://github.com/omidzed/ajax-project/assets/136918229/2493e259-1124-4c1e-817c-b2d0ac4e94ce)

## ✅ Task List
- **Create the Home Page**
- [ ] Create the remaining HTML for the header
  - [ ]  Complete the index.HTML  using the appropriate responsive layout classes.
  - [ ] Write CSS for mobile devices first.
  - [ ] Adjust styling to fluidly adapt to desktop.
  - [ ] Below the header, create the HTML for the home page view, `data-view="home-page"` element that renders a `<ul>` which will be created from our upcoming API call. 
- [ ] Make sure all targets the user can interact with look and behave properly
  - [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
  - [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Add an empty unordered list to the `div[data-view="home-page"]` element in the HTML.
- [ ] Define a function named `renderAsset` with a single parameter called `asset` . It will represent one of the assets returned from the array returned from `data.assets`,  which the call to the coinMarketCap API produced. 
- [ ] Add an event listener for the DOMContentLoaded event to make sure your JavaScript runs after the HTML has fully loaded.
  - [ ] Create this event listener by writing function initializeApp( ) 
  - [ ]  initializeApp( ) should make a call to the coinMarketCap API for the data to be stored in `data.assets` which will be used to render the `<li>` elements in our `<ul>` on the Home Page.
 
- **Search box functionality**
- [ ] Add an 'input' event listener to the Search input that filters the data array from coinMarketCap to just the one asset the user looked up, call it `handleSearch `
  - [ ] Inside the `handleSearch` function, get the current value of the search box.
  - [ ] Filter the list of the 100 assets from data.assets based on the search input.
  - [ ] Render the filtered list using the `render( )` function.

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
